const models = require('../../models');
const knex = require('knex');

const profiles = [
  {
    first: 'John',
    last: 'Lennon',
    display: 'johnlennon',
    email: 'john@lennon.com',
    bio: 'I started the beatles...',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
  {
    first: 'Trey',
    last: 'Anastasio',
    display: 'treyanastasio',
    email: 'trey@phish.com',
    bio: 'gamehenge 4 life',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
  {
    first: 'Jake',
    last: 'Cinninger',
    display: 'JakeCinninger',
    email: 'Jake@Cinninger.com',
    bio: 'always melting face',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
  {
    first: 'Miles',
    last: 'Davis',
    display: 'MilesDavis',
    email: 'Miles@Davis.com',
    bio: 'cool cat',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
  {
    first: 'Herbie',
    last: 'Hancock',
    display: 'HerbieHancock',
    email: 'Herbie@Hancock.com',
    bio: 'fat albert',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
  {
    first: 'Stewart',
    last: 'Copeland',
    display: 'StewartCopeland',
    email: 'Stewart@Copeland.com',
    bio: 'keeping time',
    zipcode: '94103',
    search_radius: 5,
    age: 40,
    gender: 'Male',
    geo: knex.raw('ST_SetSRID( ST_Point(37.7726402, -122.4099154) , 4326)'),
  },
];

module.exports = () => Promise.all(profiles.map(profile => models.Profile.forge(profile).save()));
